# Python basics (numpy) 

It's a great opportunity to discover some very general tips about Python !

Define variables...

In [1]:
x = 3

In [2]:
x + 3

6

Now you can declare a string

In [3]:
sentence = "This is just a string"

Slice it

In [5]:
sentence[0:6]

'This i'

Create lists

In [6]:
random_list = [3, 5, 6, 'aa']

In [36]:
type(random_list)

list

Select the last element of it using `-1` 

In [7]:
random_list[-1]

'aa'

Quite pythonic way to do a `for` in one line : keeping elements of the list only if they're not strings

In [8]:
[element for element in random_list if type(element) != str]

[3, 5, 6]

How to write a function in python :

In [9]:
def f(x):
    return x**2

In [10]:
f(0)

0

In [11]:
f(1)

1

You can have more than one argument, and also default arguments

In [12]:
def g(x, d=2):
    return x**d

In [13]:
g(4)

16

In [14]:
g(4,3)

64

You can play around with these, but eventually it's all pretty similar to other languages (MATLAB, R)

In [37]:
sentence.split()

['This', 'is', 'just', 'a', 'string']

In [38]:
sentence.split('s')

['Thi', ' i', ' ju', 't a ', 'tring']

In [39]:
" ".join(sentence.split())

'This is just a string'

In [41]:
[0]*12

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [44]:
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# Numpy 

I highly advise to run into these tutorials of Numpy to get along with numerical representation using Python

https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html

In [15]:
import numpy as np

In [16]:
a = np.arange(15).reshape(3, 5)

In [17]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
a.shape

(3, 5)

In [19]:
a.ndim

2

In [20]:
b = np.array([6, 7, 8])

In [21]:
b

array([6, 7, 8])

In [22]:
b += 1

In [23]:
b

array([7, 8, 9])

In [27]:
b + 2

array([ 9, 10, 11])

In [28]:
type(b)

numpy.ndarray

In [29]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [30]:
np.ones( (3,3) )

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [31]:
np.random.random((2,3))

array([[ 0.08990536,  0.6308372 ,  0.64751498],
       [ 0.58380671,  0.62455646,  0.0789133 ]])

In [32]:
b = np.arange(12).reshape(3,4)

In [34]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [35]:
np.sqrt(b)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974,  2.64575131],
       [ 2.82842712,  3.        ,  3.16227766,  3.31662479]])